#!/usr/bin/env python3
import argparse
import gzip
from pathlib import Path


def to_c_array(data: bytes, cols: int = 12) -> str:
    hexes = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(hexes), cols):
        lines.append("    " + ", ".join(hexes[i:i + cols]) + ",")
    return "\n".join(lines)


def gzip_bytes(src: bytes) -> bytes:
    return gzip.compress(src, compresslevel=9, mtime=0)


def render_header(index_gz: bytes, favicon_gz: bytes) -> str:
    return f"""// Auto-generated by utils/gen_htdocs.py. Do not edit manually.

#ifndef HTDOCS_H
#define HTDOCS_H

#include <stdint.h>

// File: favicon.ico.gz, Size: {len(favicon_gz)}
#define favicon_ico_gz_len {len(favicon_gz)}
const uint8_t favicon_ico_gz[] = {{
{to_c_array(favicon_gz)}
}};

// File: index.html.gz, Size: {len(index_gz)}
#define index_html_gz_len {len(index_gz)}
const uint8_t index_html_gz[] = {{
{to_c_array(index_gz)}
}};

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate htdocs.h from static assets")
    parser.add_argument("--index", required=True, help="Path to index.html")
    parser.add_argument("--favicon", required=True, help="Path to favicon.ico")
    parser.add_argument("--output", required=True, help="Path to output htdocs.h")
    args = parser.parse_args()

    index_path = Path(args.index)
    favicon_path = Path(args.favicon)
    output_path = Path(args.output)

    index_raw = index_path.read_bytes()
    favicon_raw = favicon_path.read_bytes()

    index_gz = gzip_bytes(index_raw)
    favicon_gz = gzip_bytes(favicon_raw)

    content = render_header(index_gz=index_gz, favicon_gz=favicon_gz)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
        return 0

    output_path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
